# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  # name: .github
  description: ":atom: Github actions blueprint repository."
  topics: ivank, github, blueprint, accelerator
  homepage: https://github.com/workflow-actions/blueprint-github-action
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  has_pages: false
  is_template: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: false

branches:
- name: main
