name: 01.build-test-run

on:
  workflow_dispatch:
  # rebuild any PRs and main branch changes
  pull_request:
    branches: [$default-branch, main]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  push:
    branches:
      - $default-branch
      - main
      - 'releases/*'
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build: # make sure we can build action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
