name: test.stuff

on:
  workflow_dispatch:

jobs:
  show:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.7.0

      - name: calculate date
        id: envs
        run: echo "::set-output name=CURRENT_DATE::$(date -u +'%Y-%m-%dT%H-%M')"

      - name: show date
        run: |
          echo "${{steps.envs.outputs.current_date}}"

      - name: show github vars
        run: echo " ${{ toJson(github) }}"